insurance_project/insurance/urls.py
from django.urls import path
from django.shortcuts import redirect
from .views import CustomLoginView, CustomLogoutView, assign_default_user_to_insured_persons, create_policy_for_user
from . import views


urlpatterns = [
    # Přesměrování na seznam pojištěnců
    path('', lambda request: redirect('insured_list'), name='index'),

    # Seznam pojištěnců
    path('seznam/', views.index, name='insured_list'),

    # Detail konkrétního pojištěnce
    path('pojistenec/<int:id>/', views.insured_detail, name='insured_detail'),

    # Přidání nového pojištěnce
    path('pojistenec/pridat/', views.add_insured, name='add_insured'),

    # Editace pojištěnce
    path('pojistenec/<int:id>/editovat/', views.edit_insured, name='edit_insured'),

    # Odstranění pojištěnce
    path('pojistenec/<int:id>/odstranit/', views.delete_insured, name='delete_insured'),

    # Seznam typů pojištění
    path('pojisteni/', views.insurance_list, name='insurance_list'),

    # Přidání nového typu pojištění
    path('pojisteni/pridat/', views.add_insurance, name='add_insurance'),

    # Editace typu pojištění
    path('pojisteni/editovat/<int:id>/', views.edit_insurance, name='edit_insurance'),

    # Odstranění typu pojištění
    path('pojisteni/odstranit/<int:id>/', views.delete_insurance, name='delete_insurance'),

    # Zobrazení seznamu pojistných krytí
    path('pojisteni/<int:id>/kryti/', views.insurance_coverage_list, name='insurance_coverage_list'),

    # Přidání pojistného krytí
    path('pojisteni/<int:insurance_id>/kryti/pridat/', views.add_or_edit_coverage, name='add_insurance_coverage'),

    # Editace pojistného krytí
    path('pojisteni/<int:insurance_id>/kryti/<int:coverage_id>/editovat/', views.add_or_edit_coverage,
         name='edit_insurance_coverage'),

    # Odstranění pojistného krytí
    path('pojisteni/<int:insurance_id>/kryti/<int:coverage_id>/odstranit/', views.delete_coverage,
         name='delete_insurance_coverage'),

    # Detail konkrétního pojištění (pojistky)
    path('pojisteni/<int:id>/', views.policy_detail, name='policy_detail'),

    # Přidání pojištění z detailu pojištěnce
    path('pojistenci/<int:insured_id>/zridit_pojistku/', views.add_policy_from_insured, name='add_policy_from_insured'),

    # Přidání pojištění z detailu pojistného krytí
    path('pojisteni/<int:coverage_id>/zridit/', views.add_policy_from_coverage, name='add_policy_from_coverage'),

    # Zřízení pojištění uživatelem
    path('pojisteni/<int:coverage_id>/zridit-uzivatelem/', create_policy_for_user, name='create_policy_for_user'),

    # Editace pojistky
    path('pojistky/<int:id>/editovat/', views.edit_policy, name='edit_policy'),

    # Odstranění pojistky
    path('pojisteni/<int:id>/odstranit/', views.delete_policy, name='delete_policy'),

    # Jak na pojištění
    path('jak-na-pojisteni/', views.how_to_insurance, name='how_to_insurance'),

    # O aplikaci
    path('o-aplikaci/', views.about, name='about'),

    # Registrace
    path('registrovat/', views.register, name='register'),

    # Přihlášení
    path('prihlasit/', CustomLoginView.as_view(template_name='insurance/login.html'), name='login'),

    # Odhlášení
    path('odhlasit/', CustomLogoutView.as_view(next_page='login'), name='logout'),

    # Přiřazení výchozího uživatele
    path('assign-default-user/', assign_default_user_to_insured_persons),
]

insurance_project/insurance_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pojisteni/', include('insurance.urls')),
    path('', lambda request: redirect('/pojisteni/', permanent=False)),
]

insurance_project/insurance/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class InsuredPerson(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField("Jméno", max_length=50)
    last_name = models.CharField("Příjmení", max_length=30)
    id_number = models.CharField("Rodné číslo", max_length=11)
    email = models.EmailField("Email")
    phone_number = models.CharField("Telefonní číslo", max_length=16)
    street_address = models.CharField("Ulice a číslo popisné", max_length=30)
    city = models.CharField("Město", max_length=30)
    postal_code = models.CharField("PSČ", max_length=6)

    def clean(self):
        """
        Metoda validace pro ověření vstupních dat před uložením do databáze.
        """
        self.validate_id_number()
        self.validate_email()
        self.validate_phone_number()
        self.validate_postal_code()

    def validate_id_number(self):
        """
        Validace rodného čísla – musí mít formát XXXXXX/XXXX a být unikátní.
        """
        if len(self.id_number) != 11 or self.id_number[6] != '/':
            raise ValidationError("Rodné číslo musí být ve formátu 'XXXXXX/XXXX.")
        existing_id_number = InsuredPerson.objects.filter(id_number=self.id_number).exclude(pk=self.pk)
        if existing_id_number.exists():
            raise ValidationError("Toto rodné číslo již bylo použito. Zadejte jiné rodné číslo.")

    def validate_email(self):
        """
        Validace emailu – email musí být unikátní.
        """
        existing_email = InsuredPerson.objects.filter(email=self.email).exclude(pk=self.pk)
        if existing_email.exists():
            raise ValidationError("Tato emailová adresa již byla použita. Zadejte jinou emailovou adresu.")

    def validate_phone_number(self):
        """
        Validace telefonního čísla – musí mít alespoň 9 a maximálně 12 číslic, a být unikátní.
        """
        numeric_value = str(self.phone_number).replace(" ", "").replace("+", "")
        if not numeric_value.isdigit() or len(numeric_value) < 9 or len(numeric_value) > 12:
            raise ValidationError("Telefonní číslo musí mít alespoň 9 a maximálně 12 číslic.")
        existing_phone_number = InsuredPerson.objects.filter(phone_number=self.phone_number).exclude(pk=self.pk)
        if existing_phone_number.exists():
            raise ValidationError("Toto telefonní číslo již bylo použito. Zadejte jiné telefonní číslo.")

    def validate_postal_code(self):
        """
        Validace PSČ – musí obsahovat přesně 5 číslic.
        """
        cleaned_postal_code = str(self.postal_code).replace(" ", "")
        if not cleaned_postal_code.isdigit() or len(cleaned_postal_code) != 5:
            raise ValidationError("PSČ musí obsahovat 5 číslic.")

    def save(self, *args, **kwargs):
        """
        Ukládá model po jeho validaci. Rodné číslo je automaticky upraveno na správný formát.
        """
        self.full_clean()

        if self.id_number and len(str(self.id_number)) == 10:
            self.id_number = str(self.id_number[:6]) + '/' + str(self.id_number[6:])

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = "Pojištěná osoba"
        verbose_name_plural = "Pojištěné osoby"


class InsuranceType(models.Model):
    name = models.CharField("Název typu pojištění", max_length=100)
    description = models.TextField("Popis typu pojištění", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Typ pojištění"
        verbose_name_plural = "Typy pojištění"


class InsuranceCoverage(models.Model):
    insurance_type = models.ForeignKey(
        InsuranceType,
        related_name='coverages',
        on_delete=models.CASCADE,
        verbose_name="Typ pojištění"
    )
    name = models.CharField(
        verbose_name="Název pojistného krytí",
        max_length=100
    )
    description = models.TextField(
        verbose_name="Popis pojistného krytí",
        blank=True
    )
    premium = models.FloatField(
        verbose_name="Pojistné",
        default=0.0
    )

    def __str__(self):
        return f"{self.insurance_type.name} - {self.name}"

    class Meta:
        verbose_name = "Pojistné krytí"
        verbose_name_plural = "Pojistná krytí"


class Policy(models.Model):
    insured_person = models.ForeignKey(
        InsuredPerson,
        related_name='policies',
        on_delete=models.CASCADE,
        verbose_name="Pojištěná osoba"
    )
    insurance_coverage = models.ForeignKey(
        InsuranceCoverage,
        on_delete=models.CASCADE,
        verbose_name="Pojistné krytí",
        null=True,
        blank=True
    )
    premium = models.FloatField(
        verbose_name="Pojistné",
        editable=False
    )
    start_date = models.DateField("Datum začátku pojištění")
    end_date = models.DateField("Datum konce pojištění")

    def __str__(self):
        return f"{self.insured_person} - {self.insurance_coverage.name} - Výše pojistného: {self.premium} Kč"

    class Meta:
        verbose_name = "Pojistka"
        verbose_name_plural = "Pojistky"

insurance_project/insurance/templates/insurance/about.html
{% extends 'insurance/base.html' %}

{% block title %}O aplikaci{% endblock %}

{% block content %}
<div class="container">
    <h1>O aplikaci</h1>


    <h2>Úvod</h2>
    <p>Tato aplikace slouží k evidenci pojištěnců a jejich pojištění. Poskytuje funkce pro správu pojištěnců,
        včetně vytváření, úprav a mazání pojištěnců a jejich pojištění.</p>


    <h2>Testování aplikace</h2>
    <p>Pokud si chcete aplikaci vyzkoušet, můžete se přihlásit pomocí následujících účtů:</p>
    <ul>
        <li><strong>Admin účet:</strong> admin, <strong>Heslo:</strong> adminheslo</li>
        <li><strong>Uživatelský účet:</strong> milda_123, <strong>Heslo:</strong> poradneheslo123*</li>
    </ul>
    <p>
        Pomocí těchto účtů si můžete vyzkoušet funkce aplikace.
        Admin účet má přístup ke všem funkcím správy pojištěnců a pojištění, zatímco uživatelský účet má omezená práva.
    </p>


    <h2>Hlavní funkce</h2>
    <ul>
        <li>Kompletní správa pojištěnců (CRUD operace).</li>
        <li>Kompletní správa pojištění.</li>
        <li>Autentizace a registrace uživatelů.</li>
        <li>Ochrana citlivých údajů prostřednictvím autentizace.</li>
        <li>Responzivní design, který zajišťuje, že aplikace vypadá dobře na různých zařízeních (časem).</li>
    </ul>


    <h2>Technologie</h2>
    <p>Při vývoji této aplikace jsem použila následující technologie:</p>
    <ul>
        <li>Django - webový framework pro vývoj aplikací v Pythonu.</li>
        <li>SQLite - lehká databáze pro ukládání dat.</li>
        <li>HTML, CSS - pro tvorbu uživatelského rozhraní.</li>
        <li>JavaScript - pro validaci formulářů na straně klienta a vylepšení interaktivity aplikace.</li>
    </ul>


    <h2>O mně</h2>
    <p>Jmenuji se Lucie Králová a jsem začínající vývojář webových aplikací.
        Tuto aplikaci jsem vyvinula jako součást svého portfolia a jako způsob, jak se naučit
        a zdokonalit své dovednosti ve vývoji webových aplikací.</p>
    <p>Pokud máte jakékoli dotazy nebo zájem o spolupráci, neváhejte mě kontaktovat.</p>

</div>
{% endblock %}

insurance_project/insurance/templates/insurance/confirm_delete.html
{% extends 'insurance/base.html' %}

{% block title %}Potvrzení smazání{% endblock %}

{% block content %}
<div class="container">
    <h1>Opravdu chcete smazat tento záznam?</h1>
    <p><strong>{{ object }}</strong></p>

    <!-- Formulář pro potvrzení smazání -->
    <form method="post" class="form-delete">
        {% csrf_token %}

        <!-- Tlačítko zpět - přesměrování zpět na seznam pojištěnců -->
        <button type="button" class="btn btn-back" onclick="window.location.href='{% url 'insured_list' %}'">
            Zpět
        </button>

        <!-- Tlačítko pro smazání záznamu -->
        <button type="submit" class="btn btn-danger">Smazat</button>

    </form>
</div>
{% endblock %}

insurance_project/insurance/templates/insurance/how_to_insurance.html
{% extends 'insurance/base.html' %}

{% block title %}
    Jak na pojištění
{% endblock %}

{% block content %}
<div class="container">
    <h1>Jak na pojištění</h1>

    <h2>Proč je důležité pojistit vašeho mazlíčka?</h2>
    <p>Pojistění domácích mazlíčků je důležité, protože vám poskytuje finanční ochranu v případě nečekaných událostí,
        jako jsou úrazy nebo nemoci vašeho mazlíčka.</p>

    <h2>Jaké druhy pojištění jsou k dispozici?</h2>
    <ul>
        <li>Základní složky pojištění domácích mazlíčků</li>
        <li>Doplňkové složky pojištění domácích mazlíčků</li>
        <li>Speciální druhy pojištění pro domácí mazlíčky</li>
        <li>Asistenční služby v rámci pojištění domácích mazlíčků</li>
    </ul>

    <h2>Jak si vybrat správné pojištění domácích mazlíčků?</h2>
    <ul>
        <li>
            <strong>Rozsah krytí:</strong> Při výběru pojištění je důležité zvážit, jaká rizika chcete pokrýt
            (nemoc, úraz, odpovědnost, krádež) a jaké jsou maximální limity plnění.
        </li>
        <li>
            <strong>Věk zvířete:</strong> Některé pojistky mají omezení týkající se věku zvířete,
            kdy například pojistná ochrana končí po dosažení určitého věku, nebo se s věkem zvyšuje pojistné.
        </li>
        <li>
            <strong>Specifické potřeby zvířete:</strong> Pokud má váš mazlíček specifické zdravotní potřeby
            nebo predispozice k určitým onemocněním, je důležité vybrat pojištění, které tyto potřeby pokrývá.
        </li>
        <li>
            <strong>Cena pojištění:</strong> Pojištění domácích mazlíčků se může výrazně lišit v ceně
            v závislosti na rozsahu krytí, věku a plemeni zvířete, a dalších faktorech.
        </li>
    </ul>

    <h2>Co je třeba vědět při uplatňování nároků na pojistné plnění?</h2>
    <ul>
        <li>
            <strong>Dokumentace a doklady:</strong>
            Při uplatňování nároku je třeba mít k dispozici veškeré lékařské zprávy, faktury za ošetření,
            policejní zprávy (v případě krádeže) a další relevantní dokumenty.
        </li>
        <li>
            <strong>Čekací lhůty:</strong> Některé pojistky mají čekací dobu,
            kdy pojištění začne plně platit až po uplynutí určité doby od uzavření pojistné smlouvy.
        </li>
        <li>
            <strong>Výluky z pojištění:</strong> Je důležité si být vědom výluk,
            které mohou zahrnovat například vrozené vady, některá onemocnění nebo škody způsobené zanedbáním péče.
        </li>
    </ul>

    <h2>Jak pojištění sjednat?</h2>
    <p>Sjednání pojištění je jednoduché, můžete tak učinit online prostřednictvím naší aplikace.</p>
</div>
{% endblock %}

insurance_project/insurance/templates/insurance/index.html
{% extends 'insurance/base.html' %}

{% block title %}
    {% if user.is_staff %}
        Seznam pojištěnců
    {% else %}
        Pojištěnec - {{ user.first_name }} {{ user.last_name }}
    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
        <h1>
            {% if user.is_staff %}
                Pojistěnci
            {% else %}
                Moje pojištění - {{ user.first_name }} {{ user.last_name }}
            {% endif %}
        </h1>

        <!-- Zobrazení zpráv pro uživatele -->
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- Tlačítko pro přidání nového pojištěnce, zobrazeno pouze administrátorům -->
        {% if user.is_staff %}
        <div class="new-insured-button-container">
            <a href="{% url 'add_insured' %}" class="btn btn-primary new-insured-button">Nový pojištěnec</a>
        </div>
        {% endif %}

        <!-- Tabulka se seznamem pojištěnců (nebo uživatelem, pokud není administrátor) -->
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Jméno</th>
                    <th>Bydliště</th>
                    <th>Akce</th>
                </tr>
            </thead>
            <tbody>
                {% for person in insured_people %}
                <tr>
                    <td>
                        <a href="{% url 'insured_detail' person.id %}">
                            {{ person.first_name }} {{ person.last_name }}
                        </a>
                    </td>
                    <td>{{ person.street_address }}, {{ person.city }}, {{ person.postal_code }}</td>
                    <td class="text-center">
                        <!-- Odkaz pro editaci záznamu pojištěnce -->
                        <a href="{% url 'edit_insured' person.id %}" class="btn btn-warning">Editovat</a>
                        <!-- Odkaz pro smazání pojištěnce, zobrazeno pouze administrátorům -->
                        {% if user.is_staff %}
                            <a href="{% url 'delete_insured' person.id %}" class="btn btn-danger">Odstranit</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Paginace (stránkování) pro seznam pojištěnců, zobrazeno pouze administrátorům -->
        {% if user.is_staff %}
        <div class="pagination">
            <span class="step-links">
                {% if insured_people.has_previous %}
                    <a href="?page={{ insured_people.previous_page_number }}" class="btn btn-light">Předchozí</a>
                {% else %}
                    <a href="#" class="btn btn-light disabled">Předchozí</a>
                {% endif %}

                {% for num in insured_people.paginator.page_range %}
                    {% if insured_people.number == num %}
                        <a href="?page={{ num }}" class="btn btn-primary">{{ num }}</a>
                    {% else %}
                        <a href="?page={{ num }}" class="btn btn-light">{{ num }}</a>
                    {% endif %}
                {% endfor %}

                {% if insured_people.has_next %}
                    <a href="?page={{ insured_people.next_page_number }}" class="btn btn-light">Další</a>
                {% else %}
                    <a href="#" class="btn btn-light disabled">Další</a>
                {% endif %}
                </span>
            </div>
        {% endif %}
</div>
{% endblock %}

insurance_project/insurance/templates/insurance/insurance_coverage_form.html
{% extends 'insurance/base.html' %}

{% block title %}
    {% if form.instance.id %}
        Editace pojistného krytí
    {% else %}
        Nové pojistné krytí
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <!-- Titulek formuláře -->
        <h1>
            {% if form.instance.id %}
                Editace pojistného krytí
            {% else %}
                Nové pojistné krytí
            {% endif %}
        </h1>

        <!-- Zobrazení případných chyb ve formuláři -->
        {% if form.errors %}
            <div class="alert alert-danger">
                <strong>Došlo k chybě:</strong>
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <!-- Formulář pro vytvoření nebo editaci pojistného krytí -->
        <form method="post" class="form-horizontal">
            {% csrf_token %}

            <!-- Pole pro zadání názvu pojistného krytí -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    {{ form.name.label_tag }}
                    {{ form.name }}
                    {% if form.name.errors %}
                        <div class="text-danger">{{ form.name.errors }}</div>
                    {% endif %}
                </div>
            </div>

            <!-- Pole pro popis pojistného krytí -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    {{ form.description.label_tag }}
                    {{ form.description|safe }}
                    {% if form.description.errors %}
                        <div class="text-danger">{{ form.description.errors }}</div>
                    {% endif %}
                </div>
            </div>

            <!-- Pole pro zadání výše pojistného -->
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.premium.label_tag }}
                    {{ form.premium }}
                    {% if form.premium.errors %}
                        <div class="text-danger">{{ form.premium.errors }}</div>
                    {% endif %}
                </div>
            </div>

            <!-- Skryté pole pro typ pojištění -->
            <input type="hidden" name="insurance_type" value="{{ insurance_type.id }}">

            <!-- Tlačítko pro uložení formuláře -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    <button type="submit" class="btn btn-save-coverage">
                        {% if form.instance.id %}
                            Uložit změny
                        {% else %}
                            Uložit
                        {% endif %}
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

insurance_project/insurance/templates/insurance/insurance_form.html
{% extends 'insurance/base.html' %}

{% block title %}
    {% if form.instance.id %}
        Editace pojištění
    {% else %}
        Nové pojištění
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <!-- Titulek stránky dle stavu (editace/vytvoření nového pojištění) -->
        <h1>
            {% if form.instance.id %}
                Editace pojištění
            {% else %}
                Nové pojištění
            {% endif %}
        </h1>

        <!-- Formulář pro vytvoření nebo editaci pojištění -->
        <form method="post" class="form-horizontal">
            {% csrf_token %}

            <!-- Automatické zobrazení všech polí formuláře pomocí as_p -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    <!-- Zobrazení formuláře s formátováním ve stylu odstavců -->
                    {{ form.as_p }}
                </div>
            </div>

            <!-- Tlačítko pro uložení formuláře -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    <button type="submit" class="btn btn-primary btn-save-insurance">
                        {% if form.instance.id %}
                            Uložit změny
                        {% else %}
                            Uložit
                        {% endif %}
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

insurance_project/insurance/templates/insurance/policy_form.html
{% extends 'insurance/base.html' %}

{% block title %}
    {% if form.instance.id %}
        Editace sjednaného pojištění
    {% else %}
        Výběr pojištění
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <h1>
            {% if form.instance.id %}
                Editace sjednaného pojištění
            {% else %}
                Výběr pojištění
            {% endif %}
        </h1>

        <!-- Formulář pro vytvoření nebo editaci pojištění -->
        <form method="post" class="form-horizontal">
            {% csrf_token %}

            <!-- Výběr pojištěné osoby -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="id_insured_person">Pojištěná osoba:</label>
                    {% if not insured_person %}
                        <select id="id_insured_person" name="insured_person" class="form-control custom-select-style">
                            <option value="" selected disabled>Vyberte pojištěnou osobu</option>
                            {% for person in form.fields.insured_person.queryset %}
                                {% if form.initial.insured_person == person.id %}
                                    <option value="{{ person.id }}" selected="selected">
                                {% else %}
                                    <option value="{{ person.id }}">
                                {% endif %}
                                    {{ person.first_name }} {{ person.last_name }}
                                </option>
                            {% endfor %}
                        </select>
                    {% else %}
                        <input type="text" class="form-control"
                               value="{{ insured_person.first_name }} {{ insured_person.last_name }}" readonly>
                        <input type="hidden" name="insured_person"
                               value="{{ insured_person.id }}">
                    {% endif %}
                </div>
            </div>

            <!-- Výběr pojistného krytí -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="id_insurance_coverage">Pojistné krytí:</label>
                    {% if insurance_coverage %}
                        <input type="text" class="form-control" value="{{ insurance_coverage.name }}" readonly>
                        <input type="hidden" name="insurance_coverage" value="{{ insurance_coverage.id }}">
                    {% else %}
                        <select id="id_insurance_coverage" name="insurance_coverage"
                                class="form-control custom-select-style">
                            <option value="" selected disabled>Vyberte pojistné krytí</option>
                            {% for coverage in form.fields.insurance_coverage.queryset %}
                                {% if form.initial.insurance_coverage == coverage.id %}
                                    <option value="{{ coverage.id }}" data-premium="{{ coverage.premium }}" selected="selected">
                                {% else %}
                                    <option value="{{ coverage.id }}" data-premium="{{ coverage.premium }}">
                                {% endif %}
                                    {{ coverage }}
                                </option>
                            {% endfor %}
                        </select>
                    {% endif %}
                </div>
            </div>

            <!-- Datum začátku pojištění -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    {{ form.start_date.label_tag }}
                    {{ form.start_date }}
                </div>
            </div>

            <!-- Datum konce pojištění -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    {{ form.end_date.label_tag }}
                    {{ form.end_date }}
                </div>
            </div>

            <!-- Roční pojistné -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="id_premium">Roční pojistné:</label>
                    <input type="text" class="form-control" id="id_premium" name="premium"
                           value="{% if insurance_coverage %}{{ insurance_coverage.premium|floatformat:0 }} Kč
                                  {% elif form.instance.premium %}{{ form.instance.premium|floatformat:0 }} Kč
                                  {% else %}0 Kč{% endif %}"
                           readonly>
                </div>
            </div>

            <!-- Tlačítko pro potvrzení -->
            <div class="form-row">
                <div class="form-group col-md-12">
                    <button type="submit" class="btn btn-primary">
                        {% if form.instance.id %}
                            Potvrdit změny
                        {% else %}
                            Potvrdit
                        {% endif %}
                    </button>
                </div>
            </div>
        </form>
    </div>

    <script>
        // Nastavení výchozího data začátku pojištění a automatické nastavení data konce pojištění
        document.addEventListener('DOMContentLoaded', function() {
            const startDateInput = document.getElementById('id_start_date');
            const endDateInput = document.getElementById('id_end_date');
            const coverageSelect = document.getElementById('id_insurance_coverage');
            const premiumInput = document.getElementById('id_premium');

            // Nastavení minimálního data pro začátek pojištění
            if (!startDateInput.value) {
                const today = new Date();
                today.setDate(today.getDate() + 1);
                const minDate = today.toISOString().split('T')[0];
                startDateInput.setAttribute('min', minDate);
                startDateInput.value = minDate;
            }

            // Funkce pro nastavení data konce pojištění rok od začátku pojištění
            function updateEndDate() {
                const startDate = new Date(startDateInput.value);
                const endDate = new Date(startDate);
                endDate.setFullYear(startDate.getFullYear() + 1);
                endDateInput.value = endDate.toISOString().split('T')[0];
            }

            // Pokud je nastaveno datum začátku, nastaví se i datum konce
            if (startDateInput.value) {
                updateEndDate();
            }

            // Při změně data začátku se automaticky nastaví datum konce
            startDateInput.addEventListener('change', updateEndDate);

            // Aktualizace ročního pojistného podle vybraného krytí
            coverageSelect.addEventListener('change', function() {
                const selectedOption = coverageSelect.options[coverageSelect.selectedIndex];
                const premiumValue = selectedOption.getAttribute('data-premium');
                if (premiumValue) {
                    premiumInput.value = parseFloat(premiumValue).toFixed(0) + ',- Kč';
                } else {
                    premiumInput.value = '';
                }
            });

            // Nastavení počáteční hodnoty ročního pojistného, pokud je vybráno pojistné krytí
            const selectedOption = coverageSelect.querySelector('option:checked');
            const initialPremiumValue = selectedOption ? selectedOption.getAttribute('data-premium') : null;
            if (initialPremiumValue) {
                premiumInput.value = parseFloat(initialPremiumValue).toFixed(0) + ',- Kč';
            }

            // Pokud není nastaveno datum konce, nastaví se automaticky
            if (!endDateInput.value) {
                updateEndDate();
            }
        });
    </script>
{% endblock %}